CREATE TABLE TB_RESERVAS(
    NUMERO INTEGER PRIMARY KEY NOT NULL,
    NUMERO_QUARTO INTEGER NOT NULL,
    DATA_ENTRADA DATE NOT NULL,
    DATA_SAIDA DATE NOT NULL,
    QTDE_PESSOAS INTEGER NOT NULL
);

ALTER TABLE TB_RESERVAS 
ADD CONSTRAINT FK_TB_RESERVAS_TB_QUARTOS 
FOREIGN KEY (NUMERO_QUARTO)
REFERENCES TB_QUARTOS(NUMERO)

CREATE TABLE TB_QUARTOS(
    NUMERO INTEGER PRIMARY KEY NOT NULL,
    CATEGORIA INTEGER NOT NULL,
    MAX_PESSOAS INTEGER NOT NULL,
    VALOR_DIARIA NUMBER(6,2) NOT NULL
);


SELECT * FROM TB_QUARTOS

INSERT INTO TB_QUARTOS VALUES(1, 1, 2, 550.0)

SELECT * FROM TB_RESERVAS

INSERT INTO TB_RESERVAS(NUMERO, QTDE_PESSOAS, NUMERO_QUARTO, DATA_ENTRADA, DATA_SAIDA) VALUES (2,2,1,TO_DATE('2020-08-31','yyyy-mm-dd'),TO_DATE('2002-02-24','yyyy-mm-dd'))


INSERT INTO TB_RESERVAS(NUMERO, QTDE_PESSOAS, NUMERO_QUARTO, DATA_ENTRADA, DATA_SAIDA) VALUES (1,2,1, TO_DATE('2020-08-31','yyyy-mm-dd'),TO_DATE('2002-02-24','yyyy-mm-dd'))


