
SELECT * FROM TB_RESERVAS
--DROP TB_QUARTOS 
SELECT * FROM TB_QUARTOS
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (20, 1, 4, 400)
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (19, 1, 4, 400)
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (18, 1, 4, 400) 
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (17, 1, 4, 400)
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (16, 1, 4, 400)
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (15, 1, 4, 400)
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (14, 1, 4, 400)
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (13, 1, 4, 400)
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (12, 1, 4, 400)
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (11, 1, 4, 400)
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (10, 1, 4, 400)

INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (21, 2, 8, 800)
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (22, 2, 8, 800)
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (23, 2, 8, 800)
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (24, 2, 8, 800)
INSERT INTO TB_QUARTOS(NUMERO, CATEGORIA, MAX_PESSOAS, VALOR_DIARIA) VALUES (25, 2, 8, 800)











SELECT COUNT(*) AS QTD_RESERVADO FROM TB_RESERVAS WHERE DATA_ENTRADA <= TO_DATE('01/09/2020', 'DD/MM/YYYY') AND TO_DATE('01/09/2020', 'DD/MM/YYYY')  <= DATA_SAIDA AND DATA_ENTRADA <= TO_DATE('04/09/2020', 'DD/MM/YYYY') AND TO_DATE('04/09/2020', 'DD/MM/YYYY')  <= DATA_SAIDA AND NUMERO_QUARTO = 12

